// Mocks generated by Mockito 5.3.2 from annotations
// in bumblebee/test/feature/authentication/domain/repositories/firebase_auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bumblebee/core/exceptions/failure.dart' as _i6;
import 'package:bumblebee/feature/authentication/domain/repositories/auth-repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Stream<_i5.User?> get authStateChange => (super.noSuchMethod(
        Invocation.getter(#authStateChange),
        returnValue: _i4.Stream<_i5.User?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.User?>.empty(),
      ) as _i4.Stream<_i5.User?>);
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User?>> loginWithEmailandPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmailandPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
            _FakeEither_0<_i6.Failure, _i5.User?>(
          this,
          Invocation.method(
            #loginWithEmailandPassword,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
                _FakeEither_0<_i6.Failure, _i5.User?>(
          this,
          Invocation.method(
            #loginWithEmailandPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>);
  @override
  _i4.Future<void> sendEmailVerificationMessage() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerificationMessage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void sendResetPasswordEmail(String? email) => super.noSuchMethod(
        Invocation.method(
          #sendResetPasswordEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>
      createAccountWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #createAccountWithEmailAndPassword,
              [
                email,
                password,
              ],
            ),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
                _FakeEither_0<_i6.Failure, _i5.User?>(
              this,
              Invocation.method(
                #createAccountWithEmailAndPassword,
                [
                  email,
                  password,
                ],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
                    _FakeEither_0<_i6.Failure, _i5.User?>(
              this,
              Invocation.method(
                #createAccountWithEmailAndPassword,
                [
                  email,
                  password,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>);
  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i5.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);
}
